{{ $servicesSecrets := dict
  "backend" $.Values.backendEnvironmentSecrets
  "frontend" $.Values.frontendEnvironmentSecrets
}}

{{ range $service, $secrets := $servicesSecrets }}
---
kind: Secret
apiVersion: v1
metadata:
  name: {{ $.Values.werf.name }}-{{ $service }}
stringData: {{ $secrets | toYaml | nindent 2 }}
{{ end }}
