name: 🚀 Release

on:
  workflow_dispatch:

env:
  BUCKET: 's3://gbh-utils'
  NAME: 'envi'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: 💻 Checkout current pull-request revision code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.DEVOPS_USER_TOKEN }}

      - name: 💼 Configure Git user
        run: |
          git config user.name "gbh-devops-bot"
          git config user.email "devops@gbh.com.do"

      - name: 🟢 Configure Node.js on runner
        uses: actions/setup-node@v4
        with:
          node-version-file: '.tool-versions'

      - name: 🟡 Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ vars.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: 'us-east-1'

      - name: 📦 Install package dependencies using lockfile
        run: npm ci

      - name: 🚀 Run new version
        run: npx release-it --ci
        env:
          GITHUB_TOKEN: ${{ secrets.DEVOPS_USER_TOKEN }}

      - name: 🔵 Set up Go on runner
        uses: actions/setup-go@v4
        with:
          go-version-file: go.mod
          cache-dependency-path: go.sum

      - name: 🚀 Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          args: release --clean
        env:
          GITHUB_TOKEN: ${{secrets.DEVOPS_USER_TOKEN}}

      - name: 🚀 Upload binaries to S3
        run: aws s3 sync ./dist ${BUCKET}/${NAME}
